/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_src_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f21 CASADI_PREFIX(f21)
#define casadi_f22 CASADI_PREFIX(f22)
#define casadi_f23 CASADI_PREFIX(f23)
#define casadi_f24 CASADI_PREFIX(f24)
#define casadi_f25 CASADI_PREFIX(f25)
#define casadi_f26 CASADI_PREFIX(f26)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const int casadi_s2[4] = {0, 1, 0, 0};
static const int casadi_s3[5] = {1, 1, 0, 1, 0};
static const int casadi_s4[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const int casadi_s5[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const int casadi_s6[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const int casadi_s7[3] = {0, 0, 0};
static const int casadi_s8[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const int casadi_s9[43] = {7, 5, 0, 7, 14, 21, 28, 35, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const int casadi_s10[19] = {7, 2, 0, 7, 14, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const int casadi_s11[8] = {0, 5, 0, 0, 0, 0, 0, 0};
static const int casadi_s12[5] = {0, 2, 0, 0, 0};

/* f_fun:(states[5],controls[2],params[0],alg[0])->(xdot[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][4] : 0;
  casadi_real a1=arg[0] ? arg[0][3] : 0;
  casadi_real a2=(a0+a1);
  casadi_real a3=2.;
  a2=(a2/a3);
  a3=arg[0] ? arg[0][2] : 0;
  casadi_real a4=sin(a3);
  a4=(a2*a4);
  if (res[0]!=0) res[0][0]=a4;
  a3=cos(a3);
  a2=(a2*a3);
  if (res[0]!=0) res[0][1]=a2;
  a0=(a0-a1);
  a1=5.9999999999999998e-001;
  a0=(a0/a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1] ? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int f_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* f_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    case 3: return "alg";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_out(int i){
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}

/* g_fun:(states[5],controls[2],params[0],xdot[5],alg[0])->(zfun) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void g_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int g_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int g_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* g_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    case 3: return "xdot";
    case 4: return "alg";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_fun_name_out(int i){
  switch (i) {
    case 0: return "zfun";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* g_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* g_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* vdeFun:(i0[5],i1[2],i2[0],i3[5x5],i4[5x2],i5[0])->(o0[5x5],o1[5x2]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][2] : 0;
  casadi_real a1=sin(a0);
  casadi_real a2=5.0000000000000000e-001;
  casadi_real a3=arg[3] ? arg[3][4] : 0;
  casadi_real a4=arg[3] ? arg[3][3] : 0;
  casadi_real a5=(a3+a4);
  a5=(a2*a5);
  casadi_real a6=(a1*a5);
  casadi_real a7=arg[0] ? arg[0][4] : 0;
  casadi_real a8=arg[0] ? arg[0][3] : 0;
  a7=(a7+a8);
  a8=2.;
  a7=(a7/a8);
  a8=cos(a0);
  casadi_real a9=arg[3] ? arg[3][2] : 0;
  casadi_real a10=(a8*a9);
  a10=(a7*a10);
  a6=(a6+a10);
  if (res[0]!=0) res[0][0]=a6;
  a6=cos(a0);
  a5=(a6*a5);
  a10=sin(a0);
  a9=(a10*a9);
  a9=(a7*a9);
  a5=(a5-a9);
  if (res[0]!=0) res[0][1]=a5;
  a5=1.6666666666666667e+000;
  a3=(a3-a4);
  a3=(a5*a3);
  if (res[0]!=0) res[0][2]=a3;
  a3=0.;
  if (res[0]!=0) res[0][3]=a3;
  if (res[0]!=0) res[0][4]=a3;
  a4=arg[3] ? arg[3][9] : 0;
  a9=arg[3] ? arg[3][8] : 0;
  casadi_real a11=(a4+a9);
  a11=(a2*a11);
  casadi_real a12=(a1*a11);
  casadi_real a13=arg[3] ? arg[3][7] : 0;
  casadi_real a14=(a8*a13);
  a14=(a7*a14);
  a12=(a12+a14);
  if (res[0]!=0) res[0][5]=a12;
  a11=(a6*a11);
  a13=(a10*a13);
  a13=(a7*a13);
  a11=(a11-a13);
  if (res[0]!=0) res[0][6]=a11;
  a4=(a4-a9);
  a4=(a5*a4);
  if (res[0]!=0) res[0][7]=a4;
  if (res[0]!=0) res[0][8]=a3;
  if (res[0]!=0) res[0][9]=a3;
  a4=arg[3] ? arg[3][14] : 0;
  a9=arg[3] ? arg[3][13] : 0;
  a11=(a4+a9);
  a11=(a2*a11);
  a13=(a1*a11);
  a12=arg[3] ? arg[3][12] : 0;
  a14=(a8*a12);
  a14=(a7*a14);
  a13=(a13+a14);
  if (res[0]!=0) res[0][10]=a13;
  a11=(a6*a11);
  a12=(a10*a12);
  a12=(a7*a12);
  a11=(a11-a12);
  if (res[0]!=0) res[0][11]=a11;
  a4=(a4-a9);
  a4=(a5*a4);
  if (res[0]!=0) res[0][12]=a4;
  if (res[0]!=0) res[0][13]=a3;
  if (res[0]!=0) res[0][14]=a3;
  a4=arg[3] ? arg[3][19] : 0;
  a9=arg[3] ? arg[3][18] : 0;
  a11=(a4+a9);
  a11=(a2*a11);
  a12=(a1*a11);
  a13=arg[3] ? arg[3][17] : 0;
  a14=(a8*a13);
  a14=(a7*a14);
  a12=(a12+a14);
  if (res[0]!=0) res[0][15]=a12;
  a11=(a6*a11);
  a13=(a10*a13);
  a13=(a7*a13);
  a11=(a11-a13);
  if (res[0]!=0) res[0][16]=a11;
  a4=(a4-a9);
  a4=(a5*a4);
  if (res[0]!=0) res[0][17]=a4;
  if (res[0]!=0) res[0][18]=a3;
  if (res[0]!=0) res[0][19]=a3;
  a4=arg[3] ? arg[3][24] : 0;
  a9=arg[3] ? arg[3][23] : 0;
  a11=(a4+a9);
  a11=(a2*a11);
  a13=(a1*a11);
  a12=arg[3] ? arg[3][22] : 0;
  a8=(a8*a12);
  a8=(a7*a8);
  a13=(a13+a8);
  if (res[0]!=0) res[0][20]=a13;
  a11=(a6*a11);
  a10=(a10*a12);
  a10=(a7*a10);
  a11=(a11-a10);
  if (res[0]!=0) res[0][21]=a11;
  a4=(a4-a9);
  a4=(a5*a4);
  if (res[0]!=0) res[0][22]=a4;
  if (res[0]!=0) res[0][23]=a3;
  if (res[0]!=0) res[0][24]=a3;
  a4=arg[4] ? arg[4][4] : 0;
  a9=arg[4] ? arg[4][3] : 0;
  a11=(a4+a9);
  a11=(a2*a11);
  a10=(a1*a11);
  a12=cos(a0);
  a13=arg[4] ? arg[4][2] : 0;
  a8=(a12*a13);
  a8=(a7*a8);
  a10=(a10+a8);
  if (res[1]!=0) res[1][0]=a10;
  a11=(a6*a11);
  a0=sin(a0);
  a13=(a0*a13);
  a13=(a7*a13);
  a11=(a11-a13);
  if (res[1]!=0) res[1][1]=a11;
  a4=(a4-a9);
  a4=(a5*a4);
  if (res[1]!=0) res[1][2]=a4;
  a4=1.;
  if (res[1]!=0) res[1][3]=a4;
  if (res[1]!=0) res[1][4]=a3;
  a9=arg[4] ? arg[4][9] : 0;
  a11=arg[4] ? arg[4][8] : 0;
  a13=(a9+a11);
  a2=(a2*a13);
  a1=(a1*a2);
  a13=arg[4] ? arg[4][7] : 0;
  a12=(a12*a13);
  a12=(a7*a12);
  a1=(a1+a12);
  if (res[1]!=0) res[1][5]=a1;
  a6=(a6*a2);
  a0=(a0*a13);
  a7=(a7*a0);
  a6=(a6-a7);
  if (res[1]!=0) res[1][6]=a6;
  a9=(a9-a11);
  a5=(a5*a9);
  if (res[1]!=0) res[1][7]=a5;
  if (res[1]!=0) res[1][8]=a3;
  if (res[1]!=0) res[1][9]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void vdeFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void vdeFun_decref(void) {
}

CASADI_SYMBOL_EXPORT int vdeFun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT int vdeFun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int vdeFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}

/* adj_ERK_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0[7]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][2] : 0;
  casadi_real a1=cos(a0);
  casadi_real a2=arg[0] ? arg[0][4] : 0;
  casadi_real a3=arg[0] ? arg[0][3] : 0;
  a2=(a2+a3);
  a3=2.;
  a2=(a2/a3);
  a3=arg[3] ? arg[3][0] : 0;
  casadi_real a4=(a2*a3);
  a1=(a1*a4);
  a4=sin(a0);
  casadi_real a5=arg[3] ? arg[3][1] : 0;
  a2=(a2*a5);
  a4=(a4*a2);
  a1=(a1-a4);
  if (res[0]!=0) res[0][2]=a1;
  a1=5.0000000000000000e-001;
  a4=cos(a0);
  a4=(a4*a5);
  a0=sin(a0);
  a0=(a0*a3);
  a4=(a4+a0);
  a1=(a1*a4);
  a4=1.6666666666666667e+000;
  a0=arg[3] ? arg[3][2] : 0;
  a4=(a4*a0);
  a0=(a1-a4);
  if (res[0]!=0) res[0][3]=a0;
  a4=(a4+a1);
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[3] ? arg[3][3] : 0;
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[3] ? arg[3][4] : 0;
  if (res[0]!=0) res[0][6]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* adj_ERK_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_ERK_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_ERK_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_ERK_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

/* adj_fun:(i0[5],i1[2],i2[0],i3[7],i4[7],i5[5],i6[2],i7[2],i8[0])->(o0[7],o1[7]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=arg[3] ? arg[3][0] : 0;
  casadi_real a3=(a1-a2);
  a3=(a0*a3);
  casadi_real a4=arg[4] ? arg[4][0] : 0;
  a3=(a3*a4);
  casadi_real a5=5.9999999999999998e-001;
  a5=(a1-a5);
  casadi_real a6=(a5+a5);
  a5=sq(a5);
  casadi_real a7=arg[0] ? arg[0][1] : 0;
  casadi_real a8=1.5000000000000000e+000;
  a8=(a7-a8);
  casadi_real a9=sq(a8);
  a5=(a5+a9);
  a5=sqrt(a5);
  a9=1.0000000000000001e-001;
  casadi_real a10=(a5-a9);
  casadi_real a11=1.0000000000000000e-002;
  casadi_real a12=(a10<=a11);
  a12=(!a12);
  a11=fmax(a11,a10);
  a10=(a11+a11);
  a11=sq(a11);
  a9=(a9/a11);
  a9=(a9/a11);
  a10=(a10*a9);
  a12=(a12*a10);
  a5=(a5+a5);
  a12=(a12/a5);
  a6=(a6*a12);
  a3=(a3-a6);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[3] ? arg[3][1] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[4] ? arg[4][1] : 0;
  a4=(a4*a1);
  a8=(a8+a8);
  a8=(a8*a12);
  a4=(a4-a8);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0] ? arg[0][2] : 0;
  a1=arg[3] ? arg[3][2] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[4] ? arg[4][2] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a3=(a0*a3);
  a7=(a7+a3);
  if (res[0]!=0) res[0][2]=a7;
  a7=arg[0] ? arg[0][3] : 0;
  a3=arg[3] ? arg[3][3] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[4] ? arg[4][3] : 0;
  a4=(a4*a1);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0] ? arg[0][4] : 0;
  a1=arg[3] ? arg[3][4] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[4] ? arg[4][4] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a3=(a0*a3);
  a7=(a7+a3);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[1] ? arg[1][0] : 0;
  a3=arg[3] ? arg[3][5] : 0;
  a4=(a7-a3);
  a1=arg[4] ? arg[4][5] : 0;
  a8=(a0*a1);
  a4=(a4*a8);
  a7=(a7-a3);
  a7=(a0*a7);
  a7=(a7*a1);
  a4=(a4+a7);
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[1] ? arg[1][1] : 0;
  a7=arg[3] ? arg[3][6] : 0;
  a1=(a4-a7);
  a3=arg[4] ? arg[4][6] : 0;
  a8=(a0*a3);
  a1=(a1*a8);
  a4=(a4-a7);
  a0=(a0*a4);
  a0=(a0*a3);
  a1=(a1+a0);
  if (res[0]!=0) res[0][6]=a1;
  a1=0.;
  if (res[1]!=0) res[1][0]=a1;
  if (res[1]!=0) res[1][1]=a1;
  if (res[1]!=0) res[1][2]=a1;
  a1=arg[6] ? arg[6][0] : 0;
  if (res[1]!=0) res[1][3]=a1;
  a1=arg[6] ? arg[6][1] : 0;
  if (res[1]!=0) res[1][4]=a1;
  a1=arg[7] ? arg[7][0] : 0;
  if (res[1]!=0) res[1][5]=a1;
  a1=arg[7] ? arg[7][1] : 0;
  if (res[1]!=0) res[1][6]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adj_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adj_fun_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT int adj_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    case 5: return casadi_s0;
    case 6: return casadi_s1;
    case 7: return casadi_s1;
    case 8: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 13;
  return 0;
}

/* adjN_fun:(i0[5],i1[0],i2[5],i3[5],i4[2],i5[0])->(o0[5],o1[5]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=arg[2] ? arg[2][0] : 0;
  casadi_real a3=(a1-a2);
  a3=(a0*a3);
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3*a4);
  casadi_real a5=5.9999999999999998e-001;
  a5=(a1-a5);
  casadi_real a6=(a5+a5);
  a5=sq(a5);
  casadi_real a7=arg[0] ? arg[0][1] : 0;
  casadi_real a8=1.5000000000000000e+000;
  a8=(a7-a8);
  casadi_real a9=sq(a8);
  a5=(a5+a9);
  a5=sqrt(a5);
  a9=1.0000000000000001e-001;
  casadi_real a10=(a5-a9);
  casadi_real a11=1.0000000000000000e-002;
  casadi_real a12=(a10<=a11);
  a12=(!a12);
  a11=fmax(a11,a10);
  a10=(a11+a11);
  a11=sq(a11);
  a9=(a9/a11);
  a9=(a9/a11);
  a10=(a10*a9);
  a12=(a12*a10);
  a5=(a5+a5);
  a12=(a12/a5);
  a6=(a6*a12);
  a3=(a3-a6);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[2] ? arg[2][1] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[3] ? arg[3][1] : 0;
  a4=(a4*a1);
  a8=(a8+a8);
  a8=(a8*a12);
  a4=(a4-a8);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0] ? arg[0][2] : 0;
  a1=arg[2] ? arg[2][2] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[3] ? arg[3][2] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a3=(a0*a3);
  a7=(a7+a3);
  if (res[0]!=0) res[0][2]=a7;
  a7=arg[0] ? arg[0][3] : 0;
  a3=arg[2] ? arg[2][3] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[3] ? arg[3][3] : 0;
  a4=(a4*a1);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0] ? arg[0][4] : 0;
  a1=arg[2] ? arg[2][4] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[3] ? arg[3][4] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a0=(a0*a3);
  a7=(a7+a0);
  if (res[0]!=0) res[0][4]=a7;
  a7=0.;
  if (res[1]!=0) res[1][0]=a7;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a7;
  a7=arg[4] ? arg[4][0] : 0;
  if (res[1]!=0) res[1][3]=a7;
  a7=arg[4] ? arg[4][1] : 0;
  if (res[1]!=0) res[1][4]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adjN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adjN_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT int adjN_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adjN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 13;
  return 0;
}

/* impl_f_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0[5]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][0] : 0;
  casadi_real a1=arg[0] ? arg[0][4] : 0;
  casadi_real a2=arg[0] ? arg[0][3] : 0;
  casadi_real a3=(a1+a2);
  casadi_real a4=2.;
  a3=(a3/a4);
  a4=arg[0] ? arg[0][2] : 0;
  casadi_real a5=sin(a4);
  a5=(a3*a5);
  a0=(a0-a5);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3] ? arg[3][1] : 0;
  a4=cos(a4);
  a3=(a3*a4);
  a0=(a0-a3);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3] ? arg[3][2] : 0;
  a1=(a1-a2);
  a2=5.9999999999999998e-001;
  a1=(a1/a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3] ? arg[3][3] : 0;
  a1=arg[1] ? arg[1][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[3] ? arg[3][4] : 0;
  a1=arg[1] ? arg[1][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

/* impl_jac_f_x_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0[5x5]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  casadi_real a1=arg[0] ? arg[0][4] : 0;
  casadi_real a2=arg[0] ? arg[0][3] : 0;
  a1=(a1+a2);
  a2=2.;
  a1=(a1/a2);
  a2=arg[0] ? arg[0][2] : 0;
  casadi_real a3=cos(a2);
  a3=(a1*a3);
  a3=(-a3);
  if (res[0]!=0) res[0][10]=a3;
  a3=sin(a2);
  a1=(a1*a3);
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  a1=5.0000000000000000e-001;
  a3=sin(a2);
  casadi_real a4=(a1*a3);
  a4=(-a4);
  if (res[0]!=0) res[0][15]=a4;
  a2=cos(a2);
  a4=(a1*a2);
  a4=(-a4);
  if (res[0]!=0) res[0][16]=a4;
  a4=1.6666666666666667e+000;
  if (res[0]!=0) res[0][17]=a4;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  a3=(a1*a3);
  a3=(-a3);
  if (res[0]!=0) res[0][20]=a3;
  a1=(a1*a2);
  a1=(-a1);
  if (res[0]!=0) res[0][21]=a1;
  a1=-1.6666666666666667e+000;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_x_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_x_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_x_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_x_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}

/* impl_jac_f_u_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0[5x2]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=-1.;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_u_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_u_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_u_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_u_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* impl_jac_f_xdot_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0[5x5]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_xdot_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_xdot_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_xdot_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_xdot_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* impl_jac_f_z_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_z_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_z_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_z_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_f_z_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* impl_jac_g_x_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_x_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_x_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_g_x_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_g_x_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* impl_jac_g_u_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_u_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_u_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_g_u_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_g_u_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* impl_jac_g_z_fun:(i0[5],i1[2],i2[0],i3[5],i4[0])->(o0) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_z_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_z_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_g_z_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_g_z_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* h_fun:(states[5],controls[2],params[0])->(h[7]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0] ? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1] ? arg[1][1] : 0;
  if (res[0]!=0) res[0][6]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int h_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* h_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_out(int i){
  switch (i) {
    case 0: return "h";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int h_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* path_con_fun:(states[5],controls[2],params[0])->(general_con[]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int path_con_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_out(int i){
  switch (i) {
    case 0: return "general_con";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* path_con_N_fun:(states[5],params[0])->(general_con_N[]) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_out(int i){
  switch (i) {
    case 0: return "general_con_N";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obji_fun:(i0[5],i1[2],i2[0],i3[7],i4[7])->(o0) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=arg[3] ? arg[3][0] : 0;
  casadi_real a3=(a1-a2);
  a3=(a0*a3);
  casadi_real a4=arg[4] ? arg[4][0] : 0;
  a3=(a3*a4);
  a2=(a1-a2);
  a3=(a3*a2);
  a2=arg[0] ? arg[0][1] : 0;
  a4=arg[3] ? arg[3][1] : 0;
  casadi_real a5=(a2-a4);
  a5=(a0*a5);
  casadi_real a6=arg[4] ? arg[4][1] : 0;
  a5=(a5*a6);
  a4=(a2-a4);
  a5=(a5*a4);
  a3=(a3+a5);
  a5=arg[0] ? arg[0][2] : 0;
  a4=arg[3] ? arg[3][2] : 0;
  a6=(a5-a4);
  a6=(a0*a6);
  casadi_real a7=arg[4] ? arg[4][2] : 0;
  a6=(a6*a7);
  a5=(a5-a4);
  a6=(a6*a5);
  a3=(a3+a6);
  a6=arg[0] ? arg[0][3] : 0;
  a5=arg[3] ? arg[3][3] : 0;
  a4=(a6-a5);
  a4=(a0*a4);
  a7=arg[4] ? arg[4][3] : 0;
  a4=(a4*a7);
  a6=(a6-a5);
  a4=(a4*a6);
  a3=(a3+a4);
  a4=arg[0] ? arg[0][4] : 0;
  a6=arg[3] ? arg[3][4] : 0;
  a5=(a4-a6);
  a5=(a0*a5);
  a7=arg[4] ? arg[4][4] : 0;
  a5=(a5*a7);
  a4=(a4-a6);
  a5=(a5*a4);
  a3=(a3+a5);
  a5=arg[1] ? arg[1][0] : 0;
  a4=arg[3] ? arg[3][5] : 0;
  a6=(a5-a4);
  a6=(a0*a6);
  a7=arg[4] ? arg[4][5] : 0;
  a6=(a6*a7);
  a5=(a5-a4);
  a6=(a6*a5);
  a3=(a3+a6);
  a6=arg[1] ? arg[1][1] : 0;
  a5=arg[3] ? arg[3][6] : 0;
  a4=(a6-a5);
  a0=(a0*a4);
  a4=arg[4] ? arg[4][6] : 0;
  a0=(a0*a4);
  a6=(a6-a5);
  a0=(a0*a6);
  a3=(a3+a0);
  a0=1.0000000000000001e-001;
  a6=1.0000000000000000e-002;
  a5=5.9999999999999998e-001;
  a1=(a1-a5);
  a1=sq(a1);
  a5=1.5000000000000000e+000;
  a2=(a2-a5);
  a2=sq(a2);
  a1=(a1+a2);
  a1=sqrt(a1);
  a1=(a1-a0);
  a6=fmax(a6,a1);
  a6=sq(a6);
  a0=(a0/a6);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f17(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void obji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void obji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int obji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int obji_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 8;
  return 0;
}

/* objN_fun:(i0[5],i1[0],i2[5],i3[5])->(o0) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=arg[2] ? arg[2][0] : 0;
  casadi_real a3=(a1-a2);
  a3=(a0*a3);
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3*a4);
  a2=(a1-a2);
  a3=(a3*a2);
  a2=arg[0] ? arg[0][1] : 0;
  a4=arg[2] ? arg[2][1] : 0;
  casadi_real a5=(a2-a4);
  a5=(a0*a5);
  casadi_real a6=arg[3] ? arg[3][1] : 0;
  a5=(a5*a6);
  a4=(a2-a4);
  a5=(a5*a4);
  a3=(a3+a5);
  a5=arg[0] ? arg[0][2] : 0;
  a4=arg[2] ? arg[2][2] : 0;
  a6=(a5-a4);
  a6=(a0*a6);
  casadi_real a7=arg[3] ? arg[3][2] : 0;
  a6=(a6*a7);
  a5=(a5-a4);
  a6=(a6*a5);
  a3=(a3+a6);
  a6=arg[0] ? arg[0][3] : 0;
  a5=arg[2] ? arg[2][3] : 0;
  a4=(a6-a5);
  a4=(a0*a4);
  a7=arg[3] ? arg[3][3] : 0;
  a4=(a4*a7);
  a6=(a6-a5);
  a4=(a4*a6);
  a3=(a3+a4);
  a4=arg[0] ? arg[0][4] : 0;
  a6=arg[2] ? arg[2][4] : 0;
  a5=(a4-a6);
  a0=(a0*a5);
  a5=arg[3] ? arg[3][4] : 0;
  a0=(a0*a5);
  a4=(a4-a6);
  a0=(a0*a4);
  a3=(a3+a0);
  a0=1.0000000000000001e-001;
  a4=1.0000000000000000e-002;
  a6=5.9999999999999998e-001;
  a1=(a1-a6);
  a1=sq(a1);
  a6=1.5000000000000000e+000;
  a2=(a2-a6);
  a2=sq(a2);
  a1=(a1+a2);
  a1=sqrt(a1);
  a1=(a1-a0);
  a4=fmax(a4,a1);
  a4=sq(a4);
  a0=(a0/a4);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f18(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void objN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void objN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int objN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int objN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int objN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 8;
  return 0;
}

/* gi_fun:(i0[5],i1[2],i2[0],i3[7],i4[7])->(o0[5],o1[2]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=arg[3] ? arg[3][0] : 0;
  casadi_real a3=(a1-a2);
  a3=(a0*a3);
  casadi_real a4=arg[4] ? arg[4][0] : 0;
  a3=(a3*a4);
  casadi_real a5=5.9999999999999998e-001;
  a5=(a1-a5);
  casadi_real a6=(a5+a5);
  a5=sq(a5);
  casadi_real a7=arg[0] ? arg[0][1] : 0;
  casadi_real a8=1.5000000000000000e+000;
  a8=(a7-a8);
  casadi_real a9=sq(a8);
  a5=(a5+a9);
  a5=sqrt(a5);
  a9=1.0000000000000001e-001;
  casadi_real a10=(a5-a9);
  casadi_real a11=1.0000000000000000e-002;
  casadi_real a12=(a10<=a11);
  a12=(!a12);
  a11=fmax(a11,a10);
  a10=(a11+a11);
  a11=sq(a11);
  a9=(a9/a11);
  a9=(a9/a11);
  a10=(a10*a9);
  a12=(a12*a10);
  a5=(a5+a5);
  a12=(a12/a5);
  a6=(a6*a12);
  a3=(a3-a6);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[3] ? arg[3][1] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[4] ? arg[4][1] : 0;
  a4=(a4*a1);
  a8=(a8+a8);
  a8=(a8*a12);
  a4=(a4-a8);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0] ? arg[0][2] : 0;
  a1=arg[3] ? arg[3][2] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[4] ? arg[4][2] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a3=(a0*a3);
  a7=(a7+a3);
  if (res[0]!=0) res[0][2]=a7;
  a7=arg[0] ? arg[0][3] : 0;
  a3=arg[3] ? arg[3][3] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[4] ? arg[4][3] : 0;
  a4=(a4*a1);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0] ? arg[0][4] : 0;
  a1=arg[3] ? arg[3][4] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[4] ? arg[4][4] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a3=(a0*a3);
  a7=(a7+a3);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[1] ? arg[1][0] : 0;
  a3=arg[3] ? arg[3][5] : 0;
  a4=(a7-a3);
  a1=arg[4] ? arg[4][5] : 0;
  a8=(a0*a1);
  a4=(a4*a8);
  a7=(a7-a3);
  a7=(a0*a7);
  a7=(a7*a1);
  a4=(a4+a7);
  if (res[1]!=0) res[1][0]=a4;
  a4=arg[1] ? arg[1][1] : 0;
  a7=arg[3] ? arg[3][6] : 0;
  a1=(a4-a7);
  a3=arg[4] ? arg[4][6] : 0;
  a8=(a0*a3);
  a1=(a1*a8);
  a4=(a4-a7);
  a0=(a0*a4);
  a0=(a0*a3);
  a1=(a1+a0);
  if (res[1]!=0) res[1][1]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f19(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int gi_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gi_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 13;
  return 0;
}

/* gN_fun:(i0[5],i1[0],i2[5],i3[5])->(o0[5]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[0] ? arg[0][0] : 0;
  casadi_real a2=arg[2] ? arg[2][0] : 0;
  casadi_real a3=(a1-a2);
  a3=(a0*a3);
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3*a4);
  casadi_real a5=5.9999999999999998e-001;
  a5=(a1-a5);
  casadi_real a6=(a5+a5);
  a5=sq(a5);
  casadi_real a7=arg[0] ? arg[0][1] : 0;
  casadi_real a8=1.5000000000000000e+000;
  a8=(a7-a8);
  casadi_real a9=sq(a8);
  a5=(a5+a9);
  a5=sqrt(a5);
  a9=1.0000000000000001e-001;
  casadi_real a10=(a5-a9);
  casadi_real a11=1.0000000000000000e-002;
  casadi_real a12=(a10<=a11);
  a12=(!a12);
  a11=fmax(a11,a10);
  a10=(a11+a11);
  a11=sq(a11);
  a9=(a9/a11);
  a9=(a9/a11);
  a10=(a10*a9);
  a12=(a12*a10);
  a5=(a5+a5);
  a12=(a12/a5);
  a6=(a6*a12);
  a3=(a3-a6);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[2] ? arg[2][1] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[3] ? arg[3][1] : 0;
  a4=(a4*a1);
  a8=(a8+a8);
  a8=(a8*a12);
  a4=(a4-a8);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0] ? arg[0][2] : 0;
  a1=arg[2] ? arg[2][2] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[3] ? arg[3][2] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a3=(a0*a3);
  a7=(a7+a3);
  if (res[0]!=0) res[0][2]=a7;
  a7=arg[0] ? arg[0][3] : 0;
  a3=arg[2] ? arg[2][3] : 0;
  a4=(a7-a3);
  a4=(a0*a4);
  a1=arg[3] ? arg[3][3] : 0;
  a4=(a4*a1);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(a0*a1);
  a4=(a4+a1);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0] ? arg[0][4] : 0;
  a1=arg[2] ? arg[2][4] : 0;
  a7=(a4-a1);
  a7=(a0*a7);
  a3=arg[3] ? arg[3][4] : 0;
  a7=(a7*a3);
  a4=(a4-a1);
  a3=(a3*a4);
  a0=(a0*a3);
  a7=(a7+a0);
  if (res[0]!=0) res[0][4]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f20(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int gN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 13;
  return 0;
}

/* Hi_fun:(i0[5],i1[2],i2[0],i3[7],i4[7])->(o0[7x7]) */
static int casadi_f21(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a1;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a1;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a1;
  if (res[0]!=0) res[0][35]=a1;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a1;
  if (res[0]!=0) res[0][38]=a1;
  if (res[0]!=0) res[0][39]=a1;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a1;
  if (res[0]!=0) res[0][43]=a1;
  if (res[0]!=0) res[0][44]=a1;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a1;
  if (res[0]!=0) res[0][47]=a1;
  if (res[0]!=0) res[0][48]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Hi_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f21(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Hi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Hi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Hi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int Hi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* Hi_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Hi_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Hi_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Hi_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Hi_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* HN_fun:(i0[5],i1[0],i2[5],i3[5])->(o0[5x5]) */
static int casadi_f22(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int HN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f22(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void HN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void HN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int HN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int HN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* HN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* HN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* HN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* HN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int HN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* Ji_fun:(i0[5],i1[2],i2[0],i3[7],i4[7])->(o0[7x5],o1[7x2]) */
static int casadi_f23(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[4] ? arg[4][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  casadi_real a1=arg[4] ? arg[4][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  a1=arg[4] ? arg[4][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  a1=arg[4] ? arg[4][3] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  a1=arg[4] ? arg[4][4] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  a1=arg[4] ? arg[4][5] : 0;
  a1=sqrt(a1);
  if (res[1]!=0) res[1][5]=a1;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a0;
  if (res[1]!=0) res[1][10]=a0;
  if (res[1]!=0) res[1][11]=a0;
  if (res[1]!=0) res[1][12]=a0;
  a0=arg[4] ? arg[4][6] : 0;
  a0=sqrt(a0);
  if (res[1]!=0) res[1][13]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f23(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int Ji_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* JN_fun:(i0[5],i1[0],i2[5],i3[5])->(o0[5x5]) */
static int casadi_f24(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  casadi_real a1=arg[3] ? arg[3][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  a1=arg[3] ? arg[3][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  a1=arg[3] ? arg[3][3] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  a0=arg[3] ? arg[3][4] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f24(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void JN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void JN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int JN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int JN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* Ci_fun:(i0[5],i1[2],i2[0])->(o0[0x5],o1[0x2]) */
static int casadi_f25(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f25(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ci_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ci_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int Ci_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ci_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* CN_fun:(i0[5],i1[0])->(o0[0x5]) */
static int casadi_f26(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f26(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void CN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void CN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int CN_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int CN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int CN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
